### PR TITLE
handler: avoid panic due to slice out of range

### LINKED ISSUE #57: panic: runtime error: slice bounds out of range [:-1]
Hi there, thank you very much for this cool project!

I noticed with a certain config, the server panics when starting up efm for Python files. In my local tests, it only happens if I try to use this script as a lint-command: https://github.com/fsouza/vimfiles/blob/main/langservers/bin/blackd-format

Here's the stacktrace:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 18 [running]:
github.com/mattn/efm-langserver/langserver.(*file).wordat(0xc0001119e0, 0x13, 0x4f, 0x0, 0x1)
        /users/fsouza/.go/pkg/mod/github.com/mattn/efm-langserver@v0.0.16-0.20200706142454-0b64dd8f71a6/langserver/handler.go:134 +0x2ed
github.com/mattn/efm-langserver/langserver.(*langhandler).lint(0xc000160120, 0xc000114b00, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0)
        /users/fsouza/.go/pkg/mod/github.com/mattn/efm-langserver@v0.0.16-0.20200706142454-0b64dd8f71a6/langserver/handler.go:340 +0xc55
github.com/mattn/efm-langserver/langserver.(*langhandler).linter(0xc000160120)
        /users/fsouza/.go/pkg/mod/github.com/mattn/efm-langserver@v0.0.16-0.20200706142454-0b64dd8f71a6/langserver/handler.go:191 +0x9c
created by github.com/mattn/efm-langserver/langserver.newhandler
        /users/fsouza/.go/pkg/mod/github.com/mattn/efm-langserver@v0.0.16-0.20200706142454-0b64dd8f71a6/langserver/handler.go:82 +0x13f
```

I can try to create a small reproducer if this helps, but I was wondering if we should simply return an empty string in that handler when currPos doesn't change in the loop? Something like:

```diff
diff --git a/langserver/handler.go b/langserver/handler.go
index 6869872..4d2f159 100644
--- a/langserver/handler.go
+++ b/langserver/handler.go
@@ -131,6 +131,9 @@ func (f *File) WordAt(pos Position) string {
                }
                prevCls = currCls
        }
+       if currPos < 0 {
+               return ""
+       }
        return string(utf16.Decode(chars[prevPos:currPos]))
 }
```

### PR DESCRIPTION
**Pull request by fsouza**
Fix #57.

### CODE REVIEW

**Comment by fsouza** [comment]
(I'm trying to figure out a reliable reproducer to add to a test)

**Comment by fsouza** [comment]
I can't reproduce the issue anymore, but figured it would be a good thing to check.

The type change to satisfy the linter may be too much, but since the type is only used within the package, I figured we could simply unexport it.

**Comment by mattn** [comment]
Thank you. I want to keep `File` to be upper-case.

**Comment by fsouza** [comment]
@mattn done! 😁

**Comment by aktau** [comment]
It would be nice if this would be submitted, the server is crashing pretty often for me.

**Comment by mattn** [comment]
Ooops. Sorry, I forgot this pull-request and fixed this issue my-self. Sorry...

**Comment by mattn** [comment]
I'll close this.

**Pull request closed without merging**
