### PR TITLE
Add support for XDG_CONFIG_HOME

### PR DESCRIPTION
**Pull request by staticssleever668**
Hi, just installed this program and so far it works great, but I noticed that when launched it creates `~/.config` folder which I moved away on my system. This patch fixes this.

### CODE REVIEW

**Comment by mattn** [comment]
I want to see some 👍  for this since this might be breaking compatibility.

**Comment by staticssleever668** [comment]
Huh,seems like I have changed configuration path by accident (used `efm-languageserver` instead of `efm-langserver`), fixed it and rebased on current `master`.
Now this will only break compatibility for those who overwrote `XDG_CONFIG_HOME` environment variable but didn't workaround support for it using the `-c` argument.
There have also appeared some thumbs up reactions for this idea since then.

**Comment by itaranto** [comment]
> I want to see some +1 for this since this might be breaking compatibility.

This shouldn't break compatibility, before `$HOME/.config` was hardcoded, and now `$XDG_CONFIG_DIR` is used when defined, if not, then `$HOME/.config` will be used. 

Most Linux distros *never* set `XDG_CONFIG_DIR` so it shouldn't break anything.

**Comment by itaranto** [comment]
> Huh, seems like I accidentally changed configuration path in this patch (used `efm-languageserver` instead of `efm-langserver`). I fixed this and rebased on current `master`. Now this will only break compatibility for those, who have set the `XDG_CONFIG_HOME` environment variable, but didn't use this app with the `-c` argument (which sets configuration file path).
> 
> Also, some thumbs up reactions for this idea have appeared since then, consider giving this patch a go.

100% agree, no Linux distro (that I know of) sets `XDG_CONFIG_HOME`.

**Comment by mattn** [comment]
LGTM.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
