### PR TITLE
fix: put continuous insertions with the same line in order of applying

### PR DESCRIPTION
**Pull request by kyoh86**
fix: #281

### CODE REVIEW

**Comment by mattn** [comment]
Thank you. Does this problem only occur with neovim?

**Comment by kyoh86** [comment]
I'll check it in vim.

**Comment by kyoh86** [comment]
@mattn 
I confirmed that the issue #281 is a problem that occurs only in Neovim.
However, Neovim contributors have stated that this is the result of a fix in accordance with the LSP specification, and as a result, the fix in efm-langserver is reasonable.

When we merge this pull request, I seem to have a problem like #281 with vim+vim-lsp this time.
Perhaps the vim-lsp implementation needs to be modified as well...

**Comment by kyoh86** [comment]
@mattn 
I had neglected to mention that this change would affect other clients as well.
At a minimum I would check the README for the following clients

- vim-lsp
- coc.nvim
- Eglot
- Helix
- VSCode

Since it will take time to verify all environments, we will withdraw the request and ask for another review after the investigation.
Thank you very much.

**Pull request closed without merging**
