### PR TITLE
Remove verbose logging

### PR DESCRIPTION
**Pull request by jspricke**
This reduces the noise in log files.

### CODE REVIEW

**Comment by mattn** [comment]
What is your motivation? If it is related on neovim behaviors, you should file issue for neovim.

**Comment by jspricke** [comment]
There is no issue, just that I think the extra output is not needed and would be nice to reduce the verbosity.

**Comment by mattn** [comment]
Why verbosity? If you are using this in the IDE or text editor, it should not be appeared. What IDE or text editor do you use?

**Comment by jspricke** [comment]
I use neovim and it shows up in the log

**Comment by mattn** [comment]
That is neovim' issue. This is important logging to debugging efm-langserver for me.

**Comment by mattn** [comment]
If you want to reduce it, please add new flag -disable-logs or something.

**Comment by jspricke** [comment]
Would you be ok with moving it to a higher loglevel, say 2?

**Comment by mattn** [comment]
Did you try -q flag?

**Comment by jspricke** [comment]
Yes, but I can't set that via LSP.

**Comment by mattn** [comment]
Really? The general lsp plugin should allow you to change the arguments. ex: `deno lsp` is passing argument the `lsp`.

**Comment by jspricke** [comment]
Indeed adding `lspconfig.efm.setup.cmd = {"efm-langserver", "-q"}` works. thx!

**Pull request closed without merging**
