### PR TITLE
Support skipping textDocument/formatting with requireMarker too

### LINKED ISSUE #213: Option to skip linting/formatting if rootMarkers can't be resolved?
Hi there!

Would you take a PR adding an option or something like that to allow linting/formatting/anything else if rootMarkers can't be resolved?

For example:

- on `textDocument/formatting`, tries to find a root dir for the command using _only_ the root markers, and if that can't be found, exit early and return the contents unchanged
- on `textDocument/didChange`, tries to find a root dir for the command using _only_ the root markers, and i f one can't be found, abort early and publish an empty array of diagnostics for the provided URI
- do something similar for all other methods (I'd make sure the solution is generic enough without replicating the check everywhere)

What do you think? Is that feasible/acceptable? Thank you!

### PR DESCRIPTION
**Pull request by fsouza**
Closes #213.

### CODE REVIEW

**Comment by fsouza** [comment]
Fixed CI in #215. I can also send a PR (or update this one) documenting requireMarker.

**Comment by mattn** [comment]
LGTM. I'll  test this in later. Thanks.

**Comment by mattn** [comment]
Thank you!

**Comment by delfick** [comment]
Thanks!!!

**Comment by fsouza** [comment]
Oh I just realized that I have a bad copy and pasta test. I'll send a follow-up PR with a better test.

**Pull request merged**
