### PR TITLE
Add lint severity setting

### PR DESCRIPTION
**Pull request by ray-x**
Allow override severity

### CODE REVIEW

**Comment by mattn** [comment]
the variable severity is always updated in the for loop.

**Comment by mattn** [comment]
It should be:

```go
for scanner.Scan() {
    ...
    severity := 1
    if config.LintSeverity != 0 {
        severity = config.LintSeverity
    }
    ...
}
```

**Comment by ray-x** [comment]
Thanks, PR updated.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
